In this project I will simulate poker hands from a deck of 52 cards and using that to calculate probability of various hands. I will be using the variation of the game called Texas hold'em.

In [74]:
import numpy as np
import pandas as pd

%matplotlib inline
import matplotlib.pyplot as plt
from matplotlib import pyplot as plt
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter('ignore', FutureWarning)

This is a cell that creates the deck

In [9]:
cards = {'Suit': [], 'Rank': []}
ranks = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
# 11 = jack, 12 = queen, 13 = king
suits = ['clubs' , 'diamonds', 'hearts', 'spades']

for x in ranks:
  for y in suits:
    cards['Suit'].append(y)
    cards['Rank'].append(x)


deck = pd.DataFrame(cards)
deck

        Suit  Rank
0      clubs     1
1   diamonds     1
2     hearts     1
3     spades     1
4      clubs     2
5   diamonds     2
6     hearts     2
7     spades     2
8      clubs     3
9   diamonds     3
10    hearts     3
11    spades     3
12     clubs     4
13  diamonds     4
14    hearts     4
15    spades     4
16     clubs     5
17  diamonds     5
18    hearts     5
19    spades     5
20     clubs     6
21  diamonds     6
22    hearts     6
23    spades     6
24     clubs     7
25  diamonds     7
26    hearts     7
27    spades     7
28     clubs     8
29  diamonds     8
30    hearts     8
31    spades     8
32     clubs     9
33  diamonds     9
34    hearts     9
35    spades     9
36     clubs    10
37  diamonds    10
38    hearts    10
39    spades    10
40     clubs    11
41  diamonds    11
42    hearts    11
43    spades    11
44     clubs    12
45  diamonds    12
46    hearts    12
47    spades    12
48     clubs    13
49  diamonds    13
50    hearts    13
51    spades    13

This is a function that simulates the drawing of n cards

In [10]:
def draw(n):
  return deck.sample(n)

val = draw(7)
val

        Suit  Rank
25  diamonds     7
23    spades     6
7     spades     2
47    spades    12
16     clubs     5
28     clubs     8
45  diamonds    12

 Here is a simulation to estimate the probability of getting a pair of aces in a draw of two cards. It executes 100 simulations to find the number of attempts it takes to draw a pair of aces, and then averages them out.

In [81]:
simulations = 100
total_trials = 0
for x in range(simulations):
  doubleaces = False
  numtrials = 0
  while not doubleaces:
    pull = draw(2)
    numtrials += 1
    if (pull['Rank'].values[0] == 1) & (pull['Rank'].values[1] == 1):
        doubleaces = True
  total_trials += numtrials

average_2aces = total_trials / simulations
prob_2aces = 1/average_2aces
print("The average number of trials it took draw a pair of aces was "\
        + str(np.round(average_2aces)) + ".")
print("The probability of drawing two aces is " + str(np.round(100*prob_2aces, decimals=2)) + "%.")

The average number of trials it took draw a pair of aces was 223.0.
The probability of drawing two aces is 0.45%.

Here is a simulation to estimate the probability of getting a pair from a draw of 2 pocket cards and the flop (3 community cards)

In [80]:
#this checks if a pull is a pair
def checkPair(pull):
  pair = False
  rankList =  pull['Rank'].value_counts().values
  for x in rankList:
    if x == 2:
      pair = True
  return pair

simulations = 100
total_trials = 0 
for x in range(simulations):
  pair = False
  numtrials = 0
  while not pair:
    pull = draw(5)
    numtrials += 1
    if checkPair(pull):
      pair = True
  total_trials += numtrials

average_pair = total_trials / simulations
prob_pair = 1 / average_pair
print("The average number of trials it took draw a pair from five cards was "\
        + str(np.round(average_pair)) + ".")
print("The probability of drawing a pair from five cards is " + str(np.round(100*prob_pair, decimals=2)) + "%.")

The average number of trials it took draw a pair from five cards was 2.0.
The probability of drawing a pair from five cards is 44.25%.

Here is a simulation to estimate the probability of getting a flush (five or more cards of the same suit) from 2 pocket cards and 5 community cards

In [89]:
simulations = 100
total_trials = 0
for x in range(simulations):
  flush = False
  numtrials = 0
  while not flush:
    pull = draw(7)
    numtrials += 1
    suitlist =  pull['Suit'].value_counts().values
    for x in suitlist:
        if x >= 5:
          flush = True
  total_trials += numtrials

average_flush = total_trials / simulations
prob_flush = 1/average_flush

print("The average number of trials it took to get a flush from seven cards was "\
        + str(np.round(average_flush)) + ".")
print("The probability of getting a flush from seven cards is " + str(np.round(100*prob_flush, decimals=2)) + "%.")

The average number of trials it took to get a flush from seven cards was 29.0.
The probability of getting a flush from seven cards is 3.41%.